import Foundation

/// Selectable UI language. `.system` follows the macOS preferred language.
enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case system, en, ru, fr, de, ko, ja, zh
    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .system: return Loc.t(.system)
        case .en: return "English"
        case .ru: return "Русский"
        case .fr: return "Français"
        case .de: return "Deutsch"
        case .ko: return "한국어"
        case .ja: return "日本語"
        case .zh: return "简体中文"
        }
    }

    /// Concrete language code, resolving `.system` against the OS preference.
    var code: String {
        switch self {
        case .system:
            let preferred = Locale.preferredLanguages.first ?? "en"
            if preferred.hasPrefix("zh") { return "zh" }
            for language in AppLanguage.allCases where language != .system {
                if preferred.hasPrefix(language.rawValue) { return language.rawValue }
            }
            return "en"
        default:
            return rawValue
        }
    }
}

/// Every user-facing string key.
enum LocKey: String {
    case overview, history, sensors, settings, quit
    case general, menuBar, panels
    case preview, menuBarCells, cellsHint, inMenuBar, available, dropToAdd, tapToAdd
    case defaultSet, useDefault, show, cellsShow, iconValue, labelValue, valueOnly
    case metrics, metricsHint, active, hiddenNotCollected, dropToHide, dragToHide
    case processLists, showProcessLists, topProcesses, cpuSection, memorySection, diskSection
    case updates, refreshInterval, refreshHint, showHistoryTab, keepHistoryFor
    case temperatureUnit, system, nerdStats, nerdStatsHint
    case launchAtLogin, switchTabs, language, version
    case cpu, memory, network, disk, gpu, battery
    case download, upload, used, free, read, write, average
    case collectingProcesses, collectingHistory, readingSensors
    case charging, notCharging, cycles
    case fans, temperature, power, voltage, current
    case lastSpan, minutesShort, hourShort
    case donate
    case checkForUpdates, checkingUpdates, upToDate, updateAvailable, downloadUpdate, updateViaHomebrew
    case autoCheckUpdates, updateFailed
    case removeHint
    case reportIssue
    case diagnostics, exportLogs, revealLogs, logsHint
    case cellsHidden
    case lowPowerMode
    // Fan control
    case fanControl, enableFanControl, experimental, fanControlHint
    case fanRiskTitle, fanRiskBody, fanRiskAccept, cancel
    case fanProfile, fanSource, fanCurveLabel, fanCurveHint
    case presetAuto, presetCoolTouch, presetBalanced, presetTurbo, presetCustom
    case helperInstall, helperUninstall, helperInstalling
    case fanConflict, fanInstallFailed
    case fanAutoExplain, fanCurvePresetHint, helperNotRunning
    case sourcePower, fanTurboExplain
    case turboInGame, turboInGameHint
}

/// Runtime localization. A global so views that re-render on a settings change pick up
/// the new language without threading a binding through every subview.
enum Loc {
    // Read and written only on the main actor (AppState / SwiftUI views).
    nonisolated(unsafe) static var language: AppLanguage = .system

    static func t(_ key: LocKey) -> String {
        let code = language.code
        return table[code]?[key] ?? table["en"]?[key] ?? key.rawValue
    }

    /// Localized string with one `%@` argument substituted.
    static func t(_ key: LocKey, _ arg: String) -> String {
        t(key).replacingOccurrences(of: "%@", with: arg)
    }

    private static let table: [String: [LocKey: String]] = [
        "en": [
            .overview: "Overview", .history: "History", .sensors: "Sensors",
            .settings: "Settings", .quit: "Quit",
            .general: "General", .menuBar: "Menu Bar", .panels: "Panels",
            .preview: "Preview", .menuBarCells: "Menu Bar Cells",
            .cellsHint: "Tap to add or remove · drag to reorder · up to 5",
            .inMenuBar: "In menu bar", .available: "Available",
            .dropToAdd: "Drop here to add", .tapToAdd: "Tap a metric below to add it",
            .defaultSet: "Default set", .useDefault: "Use default",
            .show: "Show", .cellsShow: "Cells show",
            .iconValue: "Icon + value", .labelValue: "Label + value", .valueOnly: "Value only",
            .metrics: "Metrics",
            .metricsHint: "Drag to reorder, or move to Hidden to stop collecting it. Applies to Overview and History.",
            .active: "Active", .hiddenNotCollected: "Hidden — not collected",
            .dropToHide: "Drop here to hide", .dragToHide: "Drag a metric to Hidden to stop collecting it",
            .processLists: "Process lists", .showProcessLists: "Show process lists",
            .topProcesses: "Top processes per section",
            .cpuSection: "CPU section", .memorySection: "Memory section", .diskSection: "Disk section",
            .updates: "Refresh rate", .refreshInterval: "Refresh interval",
            .refreshHint: "Polls 3× slower in Low Power Mode and 1.5× slower on battery.",
            .showHistoryTab: "Show History tab", .keepHistoryFor: "Keep history for",
            .temperatureUnit: "Temperature unit", .system: "System",
            .nerdStats: "Nerd stats", .nerdStatsHint: "Show voltage, current and the full sensor list.",
            .launchAtLogin: "Launch at login",
            .switchTabs: "Switch tabs",
            .language: "Language", .version: "Version",
            .cpu: "CPU", .memory: "Memory", .network: "Network", .disk: "Disk",
            .gpu: "GPU", .battery: "Battery",
            .download: "Download", .upload: "Upload", .used: "Used", .free: "free",
            .read: "Read", .write: "Write", .average: "Average",
            .collectingProcesses: "Collecting process data…",
            .collectingHistory: "Collecting history…", .readingSensors: "Reading sensors…",
            .charging: "Charging", .notCharging: "Plugged in, not charging", .cycles: "Cycles",
            .fans: "Fans", .temperature: "Temperature", .power: "Power",
            .voltage: "Voltage", .current: "Current",
            .lastSpan: "Last %@", .minutesShort: "min", .hourShort: "h",
            .donate: "Donate crypto",
            .reportIssue: "Report a bug or idea",
            .checkForUpdates: "Check for updates", .checkingUpdates: "Checking for updates…",
            .upToDate: "TinyStats is up to date", .updateAvailable: "Update available: %@",
            .downloadUpdate: "Download", .updateViaHomebrew: "Update via Homebrew",
            .autoCheckUpdates: "Check for updates automatically",
            .updateFailed: "Couldn’t check for updates",
            .removeHint: "Drag a cell here to remove it",
            .diagnostics: "Diagnostics", .exportLogs: "Export Logs…", .revealLogs: "Show in Finder",
            .logsHint: "Logs record errors and crashes. Export them and attach to a bug report.",
            .cellsHidden: "%@ cell(s) hidden — not enough room beside the notch.",
            .lowPowerMode: "Low Power Mode",
            .fanControl: "Fan Control", .enableFanControl: "Enable fan control",
            .experimental: "Experimental",
            .fanControlHint: "Drive the fans from a temperature sensor. Needs a small privileged helper, installed once with your password.",
            .fanRiskTitle: "Control fans at your own risk",
            .fanRiskBody: "Overriding fan speeds can let your Mac run hotter than Apple intends and may, in extreme cases, risk damage or reduced lifespan. TinyStats never drops a fan below its reported minimum, returns control to macOS at critical temperatures, and reverts to automatic if it stops responding — but you use this feature at your own risk.",
            .fanRiskAccept: "I understand", .cancel: "Cancel",
            .fanProfile: "Profile", .fanSource: "Driven by", .fanCurveLabel: "Curve",
            .fanCurveHint: "Drag the points to shape temperature → fan speed.",
            .presetAuto: "Auto", .presetCoolTouch: "Cool-touch", .presetBalanced: "Balanced",
            .presetTurbo: "Turbo", .presetCustom: "Custom",
            .helperInstall: "Install helper", .helperUninstall: "Remove helper",
            .helperInstalling: "Installing…", .fanConflict: "%@ is also controlling the fans. Two controllers fight each other — quit it first.",
            .fanInstallFailed: "Helper install failed: %@",
            .fanAutoExplain: "macOS controls the fans automatically.",
            .fanCurvePresetHint: "Drag any point to start your own curve.",
            .helperNotRunning: "Fan helper isn’t running.",
            .sourcePower: "Power", .fanTurboExplain: "Fans run at maximum speed.",
            .turboInGame: "Turbo while a game is active",
            .turboInGameHint: "Run fans at full speed while macOS Game Mode is on (releases automatically).",
        ],
        "ru": [
            .overview: "Обзор", .history: "История", .sensors: "Сенсоры",
            .settings: "Настройки", .quit: "Выход",
            .general: "Основные", .menuBar: "Строка меню", .panels: "Панели",
            .preview: "Предпросмотр", .menuBarCells: "Ячейки строки меню",
            .cellsHint: "Нажмите чтобы добавить/убрать · перетащите для порядка · до 5",
            .inMenuBar: "В строке меню", .available: "Доступные",
            .dropToAdd: "Отпустите, чтобы добавить", .tapToAdd: "Нажмите метрику ниже, чтобы добавить",
            .defaultSet: "Набор по умолчанию", .useDefault: "По умолчанию",
            .show: "Отображение", .cellsShow: "Ячейки показывают",
            .iconValue: "Значок + значение", .labelValue: "Подпись + значение", .valueOnly: "Только значение",
            .metrics: "Метрики",
            .metricsHint: "Перетащите для порядка или в «Скрытые», чтобы не собирать. Влияет на Обзор и Историю.",
            .active: "Активные", .hiddenNotCollected: "Скрытые — не собираются",
            .dropToHide: "Отпустите, чтобы скрыть", .dragToHide: "Перетащите метрику в «Скрытые», чтобы не собирать",
            .processLists: "Списки процессов", .showProcessLists: "Показывать списки процессов",
            .topProcesses: "Топ процессов в секции",
            .cpuSection: "Секция CPU", .memorySection: "Секция памяти", .diskSection: "Секция диска",
            .updates: "Частота обновления", .refreshInterval: "Интервал обновления",
            .refreshHint: "В режиме энергосбережения опрос в 3× реже, на батарее — в 1.5×.",
            .showHistoryTab: "Показывать вкладку «История»", .keepHistoryFor: "Хранить историю",
            .temperatureUnit: "Единица температуры", .system: "Система",
            .nerdStats: "Расширенные данные", .nerdStatsHint: "Показывать напряжение, ток и весь список сенсоров.",
            .launchAtLogin: "Запускать при входе",
            .switchTabs: "Переключение вкладок",
            .language: "Язык", .version: "Версия",
            .cpu: "CPU", .memory: "Память", .network: "Сеть", .disk: "Диск",
            .gpu: "GPU", .battery: "Батарея",
            .download: "Загрузка", .upload: "Отдача", .used: "Занято", .free: "свободно",
            .read: "Чтение", .write: "Запись", .average: "Среднее",
            .collectingProcesses: "Сбор данных о процессах…",
            .collectingHistory: "Сбор истории…", .readingSensors: "Чтение сенсоров…",
            .charging: "Зарядка", .notCharging: "Подключено, не заряжается", .cycles: "Циклы",
            .fans: "Вентиляторы", .temperature: "Температура", .power: "Мощность",
            .voltage: "Напряжение", .current: "Ток",
            .lastSpan: "За %@", .minutesShort: "мин", .hourShort: "ч",
            .donate: "Донат криптой",
            .reportIssue: "Сообщить о баге или идее",
            .checkForUpdates: "Проверить обновления", .checkingUpdates: "Проверка обновлений…",
            .upToDate: "Установлена последняя версия", .updateAvailable: "Доступно обновление: %@",
            .downloadUpdate: "Скачать", .updateViaHomebrew: "Обновить через Homebrew",
            .autoCheckUpdates: "Проверять обновления автоматически",
            .updateFailed: "Не удалось проверить обновления",
            .removeHint: "Перетащите ячейку сюда, чтобы убрать",
            .diagnostics: "Диагностика", .exportLogs: "Экспорт логов…", .revealLogs: "Показать в Finder",
            .logsHint: "Логи фиксируют ошибки и вылеты. Экспортируйте и приложите к отчёту о баге.",
            .cellsHidden: "Скрыто ячеек: %@ — мало места рядом с чёлкой.",
            .lowPowerMode: "Режим энергосбережения",
            .fanControl: "Вентиляторы", .enableFanControl: "Управление вентиляторами",
            .experimental: "Эксперимент",
            .fanControlHint: "Управляйте вентиляторами по датчику температуры. Нужен небольшой привилегированный помощник — устанавливается один раз по паролю.",
            .fanRiskTitle: "Управление на свой страх и риск",
            .fanRiskBody: "Принудительное управление оборотами может держать Mac горячее, чем задумано Apple, и в крайних случаях грозит повреждением или сокращением срока службы. TinyStats никогда не опускает вентилятор ниже минимума, возвращает управление macOS при критической температуре и откатывается в авто при потере связи — но вы используете эту функцию на свой риск.",
            .fanRiskAccept: "Понимаю", .cancel: "Отмена",
            .fanProfile: "Профиль", .fanSource: "По датчику", .fanCurveLabel: "Кривая",
            .fanCurveHint: "Перетаскивайте точки: температура → обороты.",
            .presetAuto: "Авто", .presetCoolTouch: "Прохладный", .presetBalanced: "Баланс",
            .presetTurbo: "Турбо", .presetCustom: "Свой",
            .helperInstall: "Установить помощник", .helperUninstall: "Удалить помощник",
            .helperInstalling: "Установка…", .fanConflict: "%@ тоже управляет вентиляторами. Два контроллера конфликтуют — сначала закройте его.",
            .fanInstallFailed: "Не удалось установить помощник: %@",
            .fanAutoExplain: "Вентиляторами управляет macOS.",
            .fanCurvePresetHint: "Потяните любую точку, чтобы создать свою кривую.",
            .helperNotRunning: "Помощник вентиляторов не запущен.",
            .sourcePower: "Питание", .fanTurboExplain: "Вентиляторы работают на максимуме.",
            .turboInGame: "Turbo во время игры",
            .turboInGameHint: "Полные обороты, пока включён Game Mode в macOS (снимается автоматически).",
        ],
        "fr": [
            .overview: "Aperçu", .history: "Historique", .sensors: "Capteurs",
            .settings: "Réglages", .quit: "Quitter",
            .general: "Général", .menuBar: "Barre menu", .panels: "Panneaux",
            .preview: "Aperçu", .menuBarCells: "Cellules de la barre",
            .cellsHint: "Touchez pour ajouter/retirer · glissez pour réordonner · jusqu’à 5",
            .inMenuBar: "Dans la barre", .available: "Disponibles",
            .dropToAdd: "Déposez ici pour ajouter", .tapToAdd: "Touchez une métrique ci-dessous",
            .defaultSet: "Ensemble par défaut", .useDefault: "Par défaut",
            .show: "Affichage", .cellsShow: "Les cellules affichent",
            .iconValue: "Icône + valeur", .labelValue: "Libellé + valeur", .valueOnly: "Valeur seule",
            .metrics: "Métriques",
            .metricsHint: "Glissez pour réordonner, ou vers Masqué pour ne plus collecter. S’applique à Aperçu et Historique.",
            .active: "Actives", .hiddenNotCollected: "Masquées — non collectées",
            .dropToHide: "Déposez ici pour masquer", .dragToHide: "Glissez une métrique vers Masqué",
            .processLists: "Listes de processus", .showProcessLists: "Afficher les listes de processus",
            .topProcesses: "Top processus par section",
            .cpuSection: "Section CPU", .memorySection: "Section mémoire", .diskSection: "Section disque",
            .updates: "Fréquence d’actualisation", .refreshInterval: "Intervalle d’actualisation",
            .refreshHint: "3× plus lent en mode économie d’énergie et 1,5× sur batterie.",
            .showHistoryTab: "Afficher l’onglet Historique", .keepHistoryFor: "Conserver l’historique",
            .temperatureUnit: "Unité de température", .system: "Système",
            .nerdStats: "Stats avancées", .nerdStatsHint: "Affiche tension, courant et tous les capteurs.",
            .launchAtLogin: "Ouvrir à la connexion",
            .switchTabs: "Changer d’onglet",
            .language: "Langue", .version: "Version",
            .cpu: "CPU", .memory: "Mémoire", .network: "Réseau", .disk: "Disque",
            .gpu: "GPU", .battery: "Batterie",
            .download: "Réception", .upload: "Envoi", .used: "Utilisé", .free: "libre",
            .read: "Lecture", .write: "Écriture", .average: "Moyenne",
            .collectingProcesses: "Collecte des processus…",
            .collectingHistory: "Collecte de l’historique…", .readingSensors: "Lecture des capteurs…",
            .charging: "En charge", .notCharging: "Branché, pas en charge", .cycles: "Cycles",
            .fans: "Ventilateurs", .temperature: "Température", .power: "Puissance",
            .voltage: "Tension", .current: "Courant",
            .lastSpan: "Dernières %@", .minutesShort: "min", .hourShort: "h",
            .donate: "Faire un don en crypto",
            .reportIssue: "Signaler un bug ou une idée",
            .checkForUpdates: "Rechercher des mises à jour", .checkingUpdates: "Recherche de mises à jour…",
            .upToDate: "TinyStats est à jour", .updateAvailable: "Mise à jour disponible : %@",
            .downloadUpdate: "Télécharger", .updateViaHomebrew: "Mettre à jour via Homebrew",
            .autoCheckUpdates: "Rechercher les mises à jour automatiquement",
            .updateFailed: "Échec de la recherche de mises à jour",
            .removeHint: "Glissez une cellule ici pour la retirer",
            .diagnostics: "Diagnostic", .exportLogs: "Exporter les journaux…", .revealLogs: "Afficher dans le Finder",
            .logsHint: "Les journaux enregistrent erreurs et plantages. Exportez-les et joignez-les à un rapport de bug.",
            .cellsHidden: "%@ cellule(s) masquée(s) — pas assez de place près de l’encoche.",
            .lowPowerMode: "Mode économie d’énergie",
            .fanControl: "Ventilateurs", .enableFanControl: "Activer le contrôle des ventilateurs",
            .experimental: "Expérimental",
            .fanControlHint: "Pilotez les ventilateurs selon un capteur de température. Nécessite un petit assistant privilégié, installé une fois avec votre mot de passe.",
            .fanRiskTitle: "Contrôle à vos risques et périls",
            .fanRiskBody: "Forcer la vitesse des ventilateurs peut faire chauffer votre Mac plus que prévu par Apple et, dans des cas extrêmes, risquer de l’endommager ou de réduire sa durée de vie. TinyStats ne descend jamais sous le minimum d’un ventilateur, rend le contrôle à macOS aux températures critiques et revient en automatique s’il cesse de répondre — mais vous utilisez cette fonction à vos risques et périls.",
            .fanRiskAccept: "Je comprends", .cancel: "Annuler",
            .fanProfile: "Profil", .fanSource: "Piloté par", .fanCurveLabel: "Courbe",
            .fanCurveHint: "Faites glisser les points : température → vitesse.",
            .presetAuto: "Auto", .presetCoolTouch: "Au frais", .presetBalanced: "Équilibré",
            .presetTurbo: "Turbo", .presetCustom: "Perso",
            .helperInstall: "Installer l’assistant", .helperUninstall: "Supprimer l’assistant",
            .helperInstalling: "Installation…",
            .fanConflict: "%@ contrôle aussi les ventilateurs. Deux contrôleurs se gênent — quittez-le d’abord.",
            .fanInstallFailed: "Échec de l’installation de l’assistant : %@",
            .fanAutoExplain: "macOS gère les ventilateurs automatiquement.",
            .fanCurvePresetHint: "Faites glisser un point pour créer votre propre courbe.",
            .helperNotRunning: "L’assistant n’est pas actif.",
            .sourcePower: "Alim.", .fanTurboExplain: "Les ventilateurs tournent au maximum.",
            .turboInGame: "Turbo pendant un jeu",
            .turboInGameHint: "Ventilateurs à fond quand le Game Mode de macOS est actif (se désactive seul).",
        ],
        "de": [
            .overview: "Übersicht", .history: "Verlauf", .sensors: "Sensoren",
            .settings: "Einstellungen", .quit: "Beenden",
            .general: "Allgemein", .menuBar: "Menüleiste", .panels: "Bereiche",
            .preview: "Vorschau", .menuBarCells: "Menüleisten-Zellen",
            .cellsHint: "Tippen zum Hinzufügen/Entfernen · ziehen zum Ordnen · bis zu 5",
            .inMenuBar: "In der Menüleiste", .available: "Verfügbar",
            .dropToAdd: "Hier ablegen zum Hinzufügen", .tapToAdd: "Tippe unten auf eine Metrik",
            .defaultSet: "Standardsatz", .useDefault: "Standard",
            .show: "Anzeige", .cellsShow: "Zellen zeigen",
            .iconValue: "Symbol + Wert", .labelValue: "Beschriftung + Wert", .valueOnly: "Nur Wert",
            .metrics: "Metriken",
            .metricsHint: "Ziehen zum Ordnen oder zu Ausgeblendet, um nicht zu erfassen. Gilt für Übersicht und Verlauf.",
            .active: "Aktiv", .hiddenNotCollected: "Ausgeblendet — nicht erfasst",
            .dropToHide: "Hier ablegen zum Ausblenden", .dragToHide: "Metrik zu Ausgeblendet ziehen",
            .processLists: "Prozesslisten", .showProcessLists: "Prozesslisten anzeigen",
            .topProcesses: "Top-Prozesse pro Bereich",
            .cpuSection: "CPU-Bereich", .memorySection: "Speicher-Bereich", .diskSection: "Festplatten-Bereich",
            .updates: "Aktualisierungsrate", .refreshInterval: "Aktualisierungsintervall",
            .refreshHint: "3× langsamer im Energiesparmodus und 1,5× im Akkubetrieb.",
            .showHistoryTab: "Verlauf-Tab anzeigen", .keepHistoryFor: "Verlauf behalten",
            .temperatureUnit: "Temperatureinheit", .system: "System",
            .nerdStats: "Erweiterte Werte", .nerdStatsHint: "Zeigt Spannung, Strom und alle Sensoren.",
            .launchAtLogin: "Beim Anmelden öffnen",
            .switchTabs: "Tabs wechseln",
            .language: "Sprache", .version: "Version",
            .cpu: "CPU", .memory: "Speicher", .network: "Netzwerk", .disk: "Festplatte",
            .gpu: "GPU", .battery: "Akku",
            .download: "Download", .upload: "Upload", .used: "Belegt", .free: "frei",
            .read: "Lesen", .write: "Schreiben", .average: "Mittel",
            .collectingProcesses: "Prozessdaten werden erfasst…",
            .collectingHistory: "Verlauf wird erfasst…", .readingSensors: "Sensoren werden gelesen…",
            .charging: "Lädt", .notCharging: "Angeschlossen, lädt nicht", .cycles: "Zyklen",
            .fans: "Lüfter", .temperature: "Temperatur", .power: "Leistung",
            .voltage: "Spannung", .current: "Strom",
            .lastSpan: "Letzte %@", .minutesShort: "Min.", .hourShort: "Std.",
            .donate: "Mit Krypto spenden",
            .reportIssue: "Fehler oder Idee melden",
            .checkForUpdates: "Nach Updates suchen", .checkingUpdates: "Suche nach Updates…",
            .upToDate: "TinyStats ist aktuell", .updateAvailable: "Update verfügbar: %@",
            .downloadUpdate: "Laden", .updateViaHomebrew: "Über Homebrew aktualisieren",
            .autoCheckUpdates: "Automatisch nach Updates suchen",
            .updateFailed: "Suche nach Updates fehlgeschlagen",
            .removeHint: "Zelle hierher ziehen, um sie zu entfernen",
            .diagnostics: "Diagnose", .exportLogs: "Protokolle exportieren…", .revealLogs: "Im Finder zeigen",
            .logsHint: "Protokolle erfassen Fehler und Abstürze. Exportieren und dem Fehlerbericht beifügen.",
            .cellsHidden: "%@ Zelle(n) ausgeblendet — zu wenig Platz neben der Notch.",
            .lowPowerMode: "Energiesparmodus",
            .fanControl: "Lüfter", .enableFanControl: "Lüftersteuerung aktivieren",
            .experimental: "Experimentell",
            .fanControlHint: "Steuere die Lüfter über einen Temperatursensor. Benötigt einen kleinen privilegierten Helfer, der einmalig mit deinem Passwort installiert wird.",
            .fanRiskTitle: "Steuerung auf eigenes Risiko",
            .fanRiskBody: "Das Erzwingen von Lüfterdrehzahlen kann deinen Mac heißer laufen lassen als von Apple vorgesehen und in Extremfällen Schäden oder eine kürzere Lebensdauer riskieren. TinyStats geht nie unter das Minimum eines Lüfters, gibt die Kontrolle bei kritischen Temperaturen an macOS zurück und schaltet auf Automatik, wenn es nicht mehr reagiert — die Nutzung erfolgt jedoch auf eigenes Risiko.",
            .fanRiskAccept: "Verstanden", .cancel: "Abbrechen",
            .fanProfile: "Profil", .fanSource: "Gesteuert von", .fanCurveLabel: "Kurve",
            .fanCurveHint: "Ziehe die Punkte: Temperatur → Drehzahl.",
            .presetAuto: "Auto", .presetCoolTouch: "Kühl", .presetBalanced: "Ausgewogen",
            .presetTurbo: "Turbo", .presetCustom: "Eigene",
            .helperInstall: "Helfer installieren", .helperUninstall: "Helfer entfernen",
            .helperInstalling: "Installation…",
            .fanConflict: "%@ steuert ebenfalls die Lüfter. Zwei Regler stören sich — beende es zuerst.",
            .fanInstallFailed: "Helfer-Installation fehlgeschlagen: %@",
            .fanAutoExplain: "macOS steuert die Lüfter automatisch.",
            .fanCurvePresetHint: "Ziehe einen Punkt, um deine eigene Kurve zu erstellen.",
            .helperNotRunning: "Lüfter-Helfer läuft nicht.",
            .sourcePower: "Energie", .fanTurboExplain: "Die Lüfter laufen mit voller Drehzahl.",
            .turboInGame: "Turbo während eines Spiels",
            .turboInGameHint: "Volle Drehzahl, solange der Game Mode von macOS aktiv ist (schaltet sich selbst ab).",
        ],
        "ko": [
            .overview: "개요", .history: "기록", .sensors: "센서",
            .settings: "설정", .quit: "종료",
            .general: "일반", .menuBar: "메뉴 막대", .panels: "패널",
            .preview: "미리보기", .menuBarCells: "메뉴 막대 셀",
            .cellsHint: "탭하여 추가/제거 · 드래그하여 순서 변경 · 최대 5개",
            .inMenuBar: "메뉴 막대", .available: "사용 가능",
            .dropToAdd: "여기에 놓아 추가", .tapToAdd: "아래 지표를 탭하여 추가",
            .defaultSet: "기본 세트", .useDefault: "기본값",
            .show: "표시", .cellsShow: "셀 표시",
            .iconValue: "아이콘 + 값", .labelValue: "레이블 + 값", .valueOnly: "값만",
            .metrics: "지표",
            .metricsHint: "드래그하여 순서 변경, 또는 숨김으로 이동해 수집 중지. 개요와 기록에 적용됩니다.",
            .active: "활성", .hiddenNotCollected: "숨김 — 수집 안 함",
            .dropToHide: "여기에 놓아 숨기기", .dragToHide: "지표를 숨김으로 드래그",
            .processLists: "프로세스 목록", .showProcessLists: "프로세스 목록 표시",
            .topProcesses: "섹션당 상위 프로세스",
            .cpuSection: "CPU 섹션", .memorySection: "메모리 섹션", .diskSection: "디스크 섹션",
            .updates: "새로고침 빈도", .refreshInterval: "새로고침 간격",
            .refreshHint: "저전력 모드에서 3배, 배터리에서 1.5배 느리게 폴링합니다.",
            .showHistoryTab: "기록 탭 표시", .keepHistoryFor: "기록 보관 기간",
            .temperatureUnit: "온도 단위", .system: "시스템",
            .nerdStats: "고급 정보", .nerdStatsHint: "전압, 전류 및 전체 센서 목록을 표시합니다.",
            .launchAtLogin: "로그인 시 실행",
            .switchTabs: "탭 전환",
            .language: "언어", .version: "버전",
            .cpu: "CPU", .memory: "메모리", .network: "네트워크", .disk: "디스크",
            .gpu: "GPU", .battery: "배터리",
            .download: "다운로드", .upload: "업로드", .used: "사용됨", .free: "여유",
            .read: "읽기", .write: "쓰기", .average: "평균",
            .collectingProcesses: "프로세스 데이터 수집 중…",
            .collectingHistory: "기록 수집 중…", .readingSensors: "센서 읽는 중…",
            .charging: "충전 중", .notCharging: "연결됨, 충전 안 함", .cycles: "사이클",
            .fans: "팬", .temperature: "온도", .power: "전력",
            .voltage: "전압", .current: "전류",
            .lastSpan: "최근 %@", .minutesShort: "분", .hourShort: "시간",
            .donate: "암호화폐로 후원",
            .reportIssue: "버그 또는 제안 보내기",
            .checkForUpdates: "업데이트 확인", .checkingUpdates: "업데이트 확인 중…",
            .upToDate: "최신 버전입니다", .updateAvailable: "업데이트 있음: %@",
            .downloadUpdate: "다운로드", .updateViaHomebrew: "Homebrew로 업데이트",
            .autoCheckUpdates: "자동으로 업데이트 확인",
            .updateFailed: "업데이트를 확인할 수 없습니다",
            .removeHint: "셀을 여기로 끌어 제거",
            .diagnostics: "진단", .exportLogs: "로그 내보내기…", .revealLogs: "Finder에서 보기",
            .logsHint: "로그는 오류와 충돌을 기록합니다. 내보내 버그 신고에 첨부하세요.",
            .cellsHidden: "%@개 셀 숨김 — 노치 옆 공간이 부족합니다.",
            .lowPowerMode: "저전력 모드",
            .fanControl: "팬 제어", .enableFanControl: "팬 제어 활성화",
            .experimental: "실험적",
            .fanControlHint: "온도 센서로 팬을 제어합니다. 비밀번호로 한 번 설치하는 작은 권한 도우미가 필요합니다.",
            .fanRiskTitle: "사용에 따른 위험은 본인 책임",
            .fanRiskBody: "팬 속도를 강제하면 Mac이 Apple의 설계보다 뜨거워질 수 있으며, 극단적인 경우 손상이나 수명 단축의 위험이 있습니다. TinyStats는 팬의 최소값 아래로 내리지 않고, 임계 온도에서 제어를 macOS에 돌려주며, 응답이 없으면 자동으로 되돌립니다 — 그러나 이 기능의 사용은 본인 책임입니다.",
            .fanRiskAccept: "이해합니다", .cancel: "취소",
            .fanProfile: "프로필", .fanSource: "기준 센서", .fanCurveLabel: "곡선",
            .fanCurveHint: "점을 드래그하세요: 온도 → 팬 속도.",
            .presetAuto: "자동", .presetCoolTouch: "쿨", .presetBalanced: "균형",
            .presetTurbo: "터보", .presetCustom: "사용자",
            .helperInstall: "도우미 설치", .helperUninstall: "도우미 제거",
            .helperInstalling: "설치 중…",
            .fanConflict: "%@도 팬을 제어하고 있습니다. 두 제어기가 충돌합니다 — 먼저 종료하세요.",
            .fanInstallFailed: "도우미 설치 실패: %@",
            .fanAutoExplain: "macOS가 팬을 자동으로 제어합니다.",
            .fanCurvePresetHint: "아무 점이나 드래그하면 사용자 곡선이 시작됩니다.",
            .helperNotRunning: "팬 도우미가 실행되고 있지 않습니다.",
            .sourcePower: "전력", .fanTurboExplain: "팬이 최대 속도로 작동합니다.",
            .turboInGame: "게임 중 터보",
            .turboInGameHint: "macOS 게임 모드가 켜져 있는 동안 팬을 최대로 (자동으로 해제).",
        ],
        "ja": [
            .overview: "概要", .history: "履歴", .sensors: "センサー",
            .settings: "設定", .quit: "終了",
            .general: "一般", .menuBar: "メニューバー", .panels: "パネル",
            .preview: "プレビュー", .menuBarCells: "メニューバーセル",
            .cellsHint: "タップで追加/削除・ドラッグで並べ替え・最大5個",
            .inMenuBar: "メニューバー内", .available: "利用可能",
            .dropToAdd: "ここにドロップして追加", .tapToAdd: "下の項目をタップして追加",
            .defaultSet: "デフォルトセット", .useDefault: "デフォルト",
            .show: "表示", .cellsShow: "セルの表示",
            .iconValue: "アイコン + 値", .labelValue: "ラベル + 値", .valueOnly: "値のみ",
            .metrics: "メトリクス",
            .metricsHint: "ドラッグで並べ替え、または「非表示」に移動して収集を停止。概要と履歴に適用されます。",
            .active: "アクティブ", .hiddenNotCollected: "非表示 — 収集なし",
            .dropToHide: "ここにドロップして非表示", .dragToHide: "項目を「非表示」へドラッグ",
            .processLists: "プロセス一覧", .showProcessLists: "プロセス一覧を表示",
            .topProcesses: "セクションごとの上位プロセス",
            .cpuSection: "CPU セクション", .memorySection: "メモリ セクション", .diskSection: "ディスク セクション",
            .updates: "更新頻度", .refreshInterval: "更新間隔",
            .refreshHint: "低電力モードで3倍、バッテリーで1.5倍ゆっくり取得します。",
            .showHistoryTab: "履歴タブを表示", .keepHistoryFor: "履歴の保持期間",
            .temperatureUnit: "温度の単位", .system: "システム",
            .nerdStats: "詳細データ", .nerdStatsHint: "電圧・電流と全センサー一覧を表示します。",
            .launchAtLogin: "ログイン時に起動",
            .switchTabs: "タブ切り替え",
            .language: "言語", .version: "バージョン",
            .cpu: "CPU", .memory: "メモリ", .network: "ネットワーク", .disk: "ディスク",
            .gpu: "GPU", .battery: "バッテリー",
            .download: "ダウンロード", .upload: "アップロード", .used: "使用中", .free: "空き",
            .read: "読み込み", .write: "書き込み", .average: "平均",
            .collectingProcesses: "プロセスデータを収集中…",
            .collectingHistory: "履歴を収集中…", .readingSensors: "センサーを読み取り中…",
            .charging: "充電中", .notCharging: "接続中、充電していません", .cycles: "サイクル",
            .fans: "ファン", .temperature: "温度", .power: "電力",
            .voltage: "電圧", .current: "電流",
            .lastSpan: "直近 %@", .minutesShort: "分", .hourShort: "時間",
            .donate: "暗号資産で寄付",
            .reportIssue: "バグ・要望を報告",
            .checkForUpdates: "アップデートを確認", .checkingUpdates: "アップデートを確認中…",
            .upToDate: "TinyStats は最新です", .updateAvailable: "アップデートあり: %@",
            .downloadUpdate: "ダウンロード", .updateViaHomebrew: "Homebrewで更新",
            .autoCheckUpdates: "アップデートを自動確認",
            .updateFailed: "アップデートを確認できませんでした",
            .removeHint: "セルをここにドラッグして削除",
            .diagnostics: "診断", .exportLogs: "ログを書き出す…", .revealLogs: "Finderで表示",
            .logsHint: "ログはエラーとクラッシュを記録します。書き出してバグ報告に添付してください。",
            .cellsHidden: "%@個のセルを非表示 — ノッチ横の余白が足りません。",
            .lowPowerMode: "低電力モード",
            .fanControl: "ファン制御", .enableFanControl: "ファン制御を有効にする",
            .experimental: "実験的",
            .fanControlHint: "温度センサーでファンを制御します。パスワードで一度だけインストールする小さな特権ヘルパーが必要です。",
            .fanRiskTitle: "自己責任での制御",
            .fanRiskBody: "ファン速度を強制すると、Appleの想定よりMacが高温になることがあり、極端な場合は故障や寿命短縮の恐れがあります。TinyStatsはファンの最小値を下回らず、危険な温度では制御をmacOSに戻し、応答しなくなれば自動に戻します — ただし本機能の使用は自己責任です。",
            .fanRiskAccept: "理解しました", .cancel: "キャンセル",
            .fanProfile: "プロファイル", .fanSource: "基準センサー", .fanCurveLabel: "カーブ",
            .fanCurveHint: "点をドラッグ：温度 → ファン速度。",
            .presetAuto: "自動", .presetCoolTouch: "クール", .presetBalanced: "バランス",
            .presetTurbo: "ターボ", .presetCustom: "カスタム",
            .helperInstall: "ヘルパーをインストール", .helperUninstall: "ヘルパーを削除",
            .helperInstalling: "インストール中…",
            .fanConflict: "%@ もファンを制御しています。2つの制御が競合します — 先に終了してください。",
            .fanInstallFailed: "ヘルパーのインストールに失敗: %@",
            .fanAutoExplain: "macOSがファンを自動で制御します。",
            .fanCurvePresetHint: "いずれかの点をドラッグするとカスタムカーブになります。",
            .helperNotRunning: "ファンヘルパーが実行されていません。",
            .sourcePower: "電力", .fanTurboExplain: "ファンは最大速度で回転します。",
            .turboInGame: "ゲーム中はターボ",
            .turboInGameHint: "macOSのゲームモードが有効な間ファンを最大に（自動で解除）。",
        ],
        "zh": [
            .overview: "概览", .history: "历史", .sensors: "传感器",
            .settings: "设置", .quit: "退出",
            .general: "通用", .menuBar: "菜单栏", .panels: "面板",
            .preview: "预览", .menuBarCells: "菜单栏单元",
            .cellsHint: "点按添加/移除 · 拖动排序 · 最多 5 个",
            .inMenuBar: "菜单栏中", .available: "可用",
            .dropToAdd: "拖到此处添加", .tapToAdd: "点按下方指标以添加",
            .defaultSet: "默认组合", .useDefault: "默认",
            .show: "显示", .cellsShow: "单元显示",
            .iconValue: "图标 + 数值", .labelValue: "标签 + 数值", .valueOnly: "仅数值",
            .metrics: "指标",
            .metricsHint: "拖动排序，或移到“隐藏”以停止采集。应用于概览和历史。",
            .active: "活动", .hiddenNotCollected: "隐藏 — 不采集",
            .dropToHide: "拖到此处隐藏", .dragToHide: "将指标拖到“隐藏”",
            .processLists: "进程列表", .showProcessLists: "显示进程列表",
            .topProcesses: "每节顶部进程",
            .cpuSection: "CPU 部分", .memorySection: "内存部分", .diskSection: "磁盘部分",
            .updates: "刷新频率", .refreshInterval: "刷新间隔",
            .refreshHint: "低电量模式下慢 3 倍，电池供电时慢 1.5 倍。",
            .showHistoryTab: "显示历史标签", .keepHistoryFor: "历史保留时长",
            .temperatureUnit: "温度单位", .system: "系统",
            .nerdStats: "高级数据", .nerdStatsHint: "显示电压、电流和完整传感器列表。",
            .launchAtLogin: "登录时启动",
            .switchTabs: "切换标签",
            .language: "语言", .version: "版本",
            .cpu: "CPU", .memory: "内存", .network: "网络", .disk: "磁盘",
            .gpu: "GPU", .battery: "电池",
            .download: "下载", .upload: "上传", .used: "已用", .free: "可用",
            .read: "读取", .write: "写入", .average: "平均",
            .collectingProcesses: "正在采集进程数据…",
            .collectingHistory: "正在采集历史…", .readingSensors: "正在读取传感器…",
            .charging: "充电中", .notCharging: "已接通，未充电", .cycles: "循环次数",
            .fans: "风扇", .temperature: "温度", .power: "功率",
            .voltage: "电压", .current: "电流",
            .lastSpan: "最近 %@", .minutesShort: "分钟", .hourShort: "小时",
            .donate: "用加密货币捐赠",
            .reportIssue: "反馈问题或建议",
            .checkForUpdates: "检查更新", .checkingUpdates: "正在检查更新…",
            .upToDate: "TinyStats 已是最新", .updateAvailable: "有可用更新：%@",
            .downloadUpdate: "下载", .updateViaHomebrew: "通过 Homebrew 更新",
            .autoCheckUpdates: "自动检查更新",
            .updateFailed: "无法检查更新",
            .removeHint: "将单元拖到此处以移除",
            .diagnostics: "诊断", .exportLogs: "导出日志…", .revealLogs: "在访达中显示",
            .logsHint: "日志记录错误和崩溃。导出并附加到错误报告中。",
            .cellsHidden: "已隐藏 %@ 个单元 — 刘海旁空间不足。",
            .lowPowerMode: "低电量模式",
            .fanControl: "风扇控制", .enableFanControl: "启用风扇控制",
            .experimental: "实验性",
            .fanControlHint: "根据温度传感器控制风扇。需要一个小型特权助手，使用密码安装一次。",
            .fanRiskTitle: "使用风险自负",
            .fanRiskBody: "强制风扇转速可能让 Mac 比 Apple 设计的更热，极端情况下有损坏或缩短寿命的风险。TinyStats 绝不会低于风扇最低转速，在临界温度时将控制权交还 macOS，并在失去响应时恢复自动 — 但使用此功能风险自负。",
            .fanRiskAccept: "我明白", .cancel: "取消",
            .fanProfile: "配置", .fanSource: "依据传感器", .fanCurveLabel: "曲线",
            .fanCurveHint: "拖动控制点：温度 → 风扇转速。",
            .presetAuto: "自动", .presetCoolTouch: "凉爽", .presetBalanced: "均衡",
            .presetTurbo: "全速", .presetCustom: "自定义",
            .helperInstall: "安装助手", .helperUninstall: "移除助手",
            .helperInstalling: "正在安装…",
            .fanConflict: "%@ 也在控制风扇。两个控制器会冲突 — 请先退出它。",
            .fanInstallFailed: "助手安装失败：%@",
            .fanAutoExplain: "macOS 自动控制风扇。",
            .fanCurvePresetHint: "拖动任意点即可创建自定义曲线。",
            .helperNotRunning: "风扇助手未运行。",
            .sourcePower: "电源", .fanTurboExplain: "风扇以最高速度运转。",
            .turboInGame: "游戏时全速",
            .turboInGameHint: "当 macOS 游戏模式开启时风扇全速（自动关闭）。",
        ],
    ]
}
